Repository CS2113-AY1819S1-T09-1/main, pull requests merged in 2018-11, with the labels that each got.

#126 Dev1 3 2
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/commons/core/JobMachineTuple.java
  src/main/java/seedu/address/commons/events/model/JobListChangedEvent.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/job/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/job/FindJobCommand.java
  src/main/java/seedu/address/logic/commands/job/ListJobsCommand.java
  src/main/java/seedu/address/logic/commands/job/ManageJobCommand.java
  src/main/java/seedu/address/logic/commands/machine/EditMachineCommand.java
  src/main/java/seedu/address/logic/commands/queue/SwapJobsCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/job/AddJobCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/TimeStamp.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/job/XmlAdaptedJob.java
  src/main/java/seedu/address/storage/job/XmlSerializableMakerManagerJobs.java
  src/main/java/seedu/address/storage/machine/XmlAdaptedJobName.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/job/JobCard.java
  src/main/java/seedu/address/ui/machine/MachineCard.java
  src/main/java/seedu/address/ui/machine/MachineListPanel.java
  src/main/resources/view/JobsListPanel.fxml
  src/main/resources/view/MachineListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/machine/MachineStatusTest.java
  src/test/java/seedu/address/storage/serializable/XmlSerializableMakerManagerJobsTest.java
  src/test/java/seedu/address/testutil/builders/JobBuilder.java
  src/test/java/seedu/address/testutil/testdata/ValidJobs.java
Labels: priority.high, severity.High, type.bug

#84 added testing codes for the job model
  data\addressbook.xml
  data\makerManagerAdmins.xml
  data\makerManagerJobs.xml
  data\makerManagerMachines.xml
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/JobName.java
  src/main/java/seedu/address/model/job/JobNote.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/job/JobNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/job/JobNameTest.java
  src/test/java/seedu/address/model/job/JobNoteTest.java
  src/test/java/seedu/address/model/job/JobOwnerTest.java
  src/test/java/seedu/address/model/job/JobTest.java
  src/test/java/seedu/address/model/job/PriorityTest.java
  src/test/java/seedu/address/model/job/StatusTest.java
  src/test/java/seedu/address/model/job/TimeStampTest.java
  src/test/java/seedu/address/model/job/UniqueJobListTest.java
  src/test/java/seedu/address/testutil/builders/JobBuilder.java
  src/test/java/seedu/address/testutil/testdata/TypicalJobs.java
Labels: priority.medium, type.testing

#127 Resolving v1.4 issues from PE1
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/machine/EditMachineCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
  src/test/java/seedu/address/model/machine/MachineEqualityTest.java
  src/test/java/seedu/address/model/machine/MachineTest.java
  src/test/java/seedu/address/model/machine/UniqueMachineListTest.java
  src/test/java/seedu/address/testutil/testdata/ValidJobs.java
Labels: priority.medium

#129 Psyf's fixes for v1.4.1
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/admin/AddAdminCommand.java
  src/main/java/seedu/address/logic/commands/job/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/job/ManageJobCommand.java
  src/main/java/seedu/address/logic/parser/job/ManageJobCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/job/JobCard.java
  src/main/java/seedu/address/ui/job/JobListPanel.java
  src/main/java/seedu/address/ui/machine/MachineListPanel.java
Labels: priority.high, severity.High, type.bug, type.docs

#134 Jj1.4features
  preferences.json
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/machine/EditMachineCommand.java
  src/main/java/seedu/address/logic/commands/machine/ManageMachineCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/machine/ManageMachineCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/machine/MachineTest.java
  src/test/java/seedu/address/model/machine/UniqueMachineListTest.java
  src/test/java/seedu/address/testutil/testdata/ValidJobs.java
Labels: priority.high

#146 Psyf1.4.2 dev
  src/main/java/seedu/address/logic/commands/job/ManageJobCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
  src/test/java/seedu/address/model/machine/UniqueMachineListTest.java
Labels: priority.high, type.enhancement

#152 Jj1.4featuresv2
  src/main/java/seedu/address/logic/commands/machine/FindMachineCommand.java
  src/main/java/seedu/address/logic/commands/machine/ManageMachineCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/machine/MachineNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
Labels: priority.medium, type.enhancement

#151 Dev1 4 2
  src/main/java/seedu/address/commons/events/ui/FocusJobRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/FocusMachineRequestEvent.java
  src/main/java/seedu/address/logic/commands/job/ManageJobCommand.java
  src/main/java/seedu/address/logic/commands/machine/EditMachineCommand.java
  src/main/java/seedu/address/logic/commands/queue/SwapJobsCommand.java
  src/main/java/seedu/address/logic/parser/job/ManageJobCommandParser.java
  src/main/java/seedu/address/logic/parser/queue/SwapJobsCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/TimeStamp.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/job/exceptions/JobOngoingException.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/main/java/seedu/address/model/machine/exceptions/MachineDisabledException.java
  src/main/java/seedu/address/ui/job/JobCard.java
  src/main/java/seedu/address/ui/job/JobListPanel.java
  src/main/java/seedu/address/ui/machine/MachineCard.java
  src/main/java/seedu/address/ui/machine/MachineListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/JobListCard.fxml
  src/main/resources/view/JobsListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/machine/MachineNameTest.java
  src/test/java/seedu/address/model/machine/MachineTest.java
  src/test/java/seedu/address/model/machine/UniqueMachineListTest.java
  src/test/java/seedu/address/testutil/testdata/ValidJobs.java
  src/test/java/seedu/address/testutil/testdata/ValidMachines.java
Labels: priority.high, type.bug, type.enhancement

#157 Multiple Changes:
  src/main/java/seedu/address/logic/commands/job/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/job/ManageJobCommand.java
  src/main/java/seedu/address/logic/commands/machine/ManageMachineCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/TimeStamp.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/main/java/seedu/address/ui/job/JobCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
Labels: priority.high, type.bug, type.enhancement

#160 Some small adjustments
  preferences.json
  src/main/java/seedu/address/logic/commands/admin/UpdatePasswordCommand.java
  src/main/java/seedu/address/logic/commands/job/ManageJobCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/admin/XmlAdaptedAdmin.java
  src/main/java/seedu/address/storage/admin/XmlSerializableMakerManagerAdmins.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
Labels: priority.medium

#161 BugFixes and Tests
  preferences.json
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/machine/AddMachineCommand.java
  src/main/java/seedu/address/logic/commands/machine/EditMachineCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/machine/AddMachineCommandParser.java
  src/main/java/seedu/address/logic/parser/machine/EditMachineCommandParser.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/main/java/seedu/address/ui/job/JobCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/JobListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/EditMachineCommandTest.java
  src/test/java/seedu/address/logic/parser/AddMachineCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditMachineCommandParserTest.java
  src/test/java/seedu/address/testutil/DefaultFailingModelStub.java
  src/test/java/seedu/address/testutil/MachineBuilder.java
  src/test/java/seedu/address/testutil/builders/EditMachineDescriptorBuilder.java
  src/test/java/seedu/address/testutil/testdata/ValidMachines.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: priority.high, type.bug, type.enhancement, type.testing
