Repository CS2113-AY1819S1-T09-1/main, pull requests merged in 2018-10, with the labels that each got.

#26 Add machine branch for UI of makerManager
  .gitignore
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/machine/AddMachineCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/machine/AddMachineCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#33 Changed implementation of Machine Status
  preferences.json
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/machine/AddMachineCommandParser.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/MachineStatus.java
  src/main/java/seedu/address/storage/machine/XmlAdaptedJobName.java
  src/main/java/seedu/address/storage/machine/XmlAdaptedMachine.java
  src/main/java/seedu/address/ui/machine/MachineCard.java
Labels: enhancement

#47 added functional Edit machine
  .gitignore
  intellij_settings_for_style.xml
  preferences.json
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/machine/AddMachineCommand.java
  src/main/java/seedu/address/logic/commands/machine/EditMachineCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/machine/AddMachineCommandParser.java
  src/main/java/seedu/address/logic/parser/machine/EditMachineCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/main/java/seedu/address/storage/machine/XmlAdaptedMachine.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.story

#43 [READY2MERGE] Unit Tests
  .gitignore
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  preferences.json
  src/main/java/seedu/address/logic/commands/admin/AddAdminCommand.java
  src/main/java/seedu/address/logic/commands/admin/LoginCommand.java
  src/main/java/seedu/address/logic/commands/admin/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/admin/PasswordValidator.java
  src/main/java/seedu/address/logic/commands/admin/RemoveAdminCommand.java
  src/main/java/seedu/address/logic/commands/admin/UpdatePasswordCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/admin/Password.java
  src/main/java/seedu/address/model/admin/Username.java
  src/main/java/seedu/address/model/job/JobOwner.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
Labels: priority.high, type.docs, type.enhancement, type.testing

#52 Last Minute Documentation for v1.2
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, status.ongoing, type.docs

#53 Documentation for v1.2
  docs/DeveloperGuide.adoc
  docs/images/Ui.png
Labels: priority.high, severity.Low, type.docs

#70 Bug Fix for non-existing preferences.json breaking app
  src/main/java/seedu/address/model/UserPrefs.java
Labels: severity.High, type.bug

#78 Auto add job
  config.json
  data\addressbook.xml
  data\makerManagerAdmins.xml
  data\makerManagerJobs.xml
  data\makerManagerMachines.xml
  preferences.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/model/machine/UniqueMachineList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
Labels: priority.medium, type.enhancement

#83 Ui Changes
  README.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  preferences.json
  src/main/java/seedu/address/logic/commands/admin/RemoveAdminCommand.java
  src/main/java/seedu/address/logic/commands/job/ManageJobCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/Status.java
  src/main/java/seedu/address/model/job/TimeStamp.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/machine/Machine.java
  src/main/java/seedu/address/storage/job/XmlAdaptedJob.java
  src/main/java/seedu/address/storage/job/XmlAdaptedTimeStamp.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/job/JobCard.java
  src/main/java/seedu/address/ui/machine/MachineCard.java
  src/main/java/seedu/address/ui/machine/MachineListPanel.java
  src/main/resources/view/JobListCard.fxml
  src/main/resources/view/MachineListCard.fxml
  src/main/resources/view/MachineListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/AddAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/RemoveAdminCommandTest.java
  src/test/java/seedu/address/logic/commands/admin/UpdatePasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/machine/AddMachineCommandTest.java
Labels: priority.high, severity.High, type.bug, type.enhancement, type.task
